# Pydantic models for request/response

from typing import Dict, List, Optional, Literal, Any, Union
from pydantic import BaseModel, Field


# Data types
DataType = Literal["integer", "boolean"]
AggregateFunction = Literal["sum", "min", "max"]
ComparisonOperator = Literal["=", "!=", ">", "<", ">=", "<="]


# Scenario Parameter
class ScenarioParameter(BaseModel):
    id: int
    name: str
    description: str
    defaultValue: Union[int, float, None] = None


# Row Level Input Variable
class RowLevelInputVariable(BaseModel):
    id: int
    name: str
    description: str
    column: str
    dataType: DataType
    min: Optional[float] = None
    max: Optional[float] = None


# Row Level Intermediate Variable
class RowLevelIntermediateVariable(BaseModel):
    id: int
    name: str
    description: str
    formula: str


# If-condition for portfolio variables
class IfCondition(BaseModel):
    column: str
    operator: ComparisonOperator
    value: str | float


# Portfolio Level Intermediate Variable
class PortfolioLevelIntermediateVariable(BaseModel):
    id: int
    name: str
    description: str
    aggregateFunction: AggregateFunction
    sourceVariables: List[str]
    groupByColumn: Optional[str] = None
    ifCondition: Optional[IfCondition] = None


# Constraint
class Constraint(BaseModel):
    id: int
    name: str
    description: str


# Objective
class Objective(BaseModel):
    id: int
    name: str
    description: str


# CSV Data
class CSVRow(BaseModel):
    data: Dict[str, Any]


class CSVData(BaseModel):
    columns: List[str]
    rows: List[CSVRow]


# Configuration state
class ConfigState(BaseModel):
    scenarioParameters: List[ScenarioParameter] = Field(default_factory=list)
    rowLevelInputVariables: List[RowLevelInputVariable] = Field(default_factory=list)
    rowLevelIntermediateVariables: List[RowLevelIntermediateVariable] = Field(default_factory=list)
    portfolioLevelIntermediateVariables: List[PortfolioLevelIntermediateVariable] = Field(default_factory=list)
    constraints: List[Constraint] = Field(default_factory=list)
    objectives: List[Objective] = Field(default_factory=list)


# Scenario data
class ScenarioInput(BaseModel):
    id: int
    name: str
    parameterValues: Dict[str, float]
    inputVariableOverrides: Dict[str, float] = {}


# Request for running a scenario
class RunScenarioRequest(BaseModel):
    config: ConfigState
    scenario: ScenarioInput
    csvData: CSVData


# Portfolio result
class PortfolioResult(BaseModel):
    variableName: str
    value: float


# Optimization result
class OptimizationResult(BaseModel):
    objectiveValue: float
    portfolioResults: List[PortfolioResult]
    constraintViolations: List[str]


# ============================================================================
# Structured CP-SAT configuration generated by LLM (no code generation)
# ============================================================================
TermType = Literal[
    "row_input",
    "row_intermediate",
    "portfolio_var",
    "column",
    "parameter",
    "constant",
]
TermOperator = Literal["<=", ">=", "=="]
ObjectiveDirection = Literal["maximize", "minimize"]


class Term(BaseModel):
    term_type: TermType = Field(
        description="The source of the data for this term."
    )
    name_or_value: Union[str, float] = Field(
        description="The prefix name, column name, parameter name, or constant value."
    )
    coefficient: Union[float, str] = Field(
        default=1.0,
        description="Multiplier for this term: numeric constant (e.g., 1.0, 5.0, -0.5) or column/parameter name for dynamic per-row coefficient (e.g., 'cost_rate', 'tax_rate').",
    )


class CPSatRowInputVariable(BaseModel):
    name_prefix: str
    min_value: Union[float, str] = Field(
        description="Numeric constant, or a column/parameter name."
    )
    max_value: Union[float, str] = Field(
        description="Numeric constant, or a column/parameter name."
    )


class CPSatRowIntermediateVariable(BaseModel):
    name_prefix: str
    terms: List[Term] = Field(
        description="The terms that sum together to equal this intermediate variable."
    )


class CPSatIfCondition(BaseModel):
    enabled: bool
    column: Optional[str] = None
    operator: Optional[Literal["==", "!=", ">", "<", ">=", "<="]] = None
    value: Optional[Union[str, float]] = None


class CPSatPortfolioVariable(BaseModel):
    portfolio_name: str
    group_by_columns: List[str] = Field(
        default=[],
        description="List of columns to group by. Empty means aggregate all.",
    )
    aggregate_function: Literal["sum", "max", "min"]
    source_row_variable: str = Field(
        description="The row-level variable prefix to aggregate."
    )
    if_condition: Optional[CPSatIfCondition] = None


class CPSatConstraint(BaseModel):
    description: str
    left_terms: List[Term]
    operator: TermOperator
    right_terms: List[Term]


class CPSatObjective(BaseModel):
    direction: ObjectiveDirection
    terms: List[Term]


class CPSatConfig(BaseModel):
    row_inputs: List[CPSatRowInputVariable] = Field(default_factory=list)
    row_intermediates: List[CPSatRowIntermediateVariable] = Field(default_factory=list)
    portfolio_variables: List[CPSatPortfolioVariable] = Field(default_factory=list)
    constraints: List[CPSatConstraint] = Field(default_factory=list)
    objective: CPSatObjective
